### PR TITLE
Debian packaging

### PR DESCRIPTION
**Pull request by iyzsong**
This PR package mu for debian(sid).
To build the deb:
```
sudo apt install devscripts
debuild -us -uc
```
I only test this on sid, I suppose ubuntu may have some minor issue.
(And we should better setup a PPA for ubuntu).

TODO:
  * Provide a svg icon.

Also, when I got segment fault when run mu with `phonon4qt5-backend-vlc`.

### CODE REVIEW

**Comment by Harinlen** [comment]
I will check the segment fault problem right now.
Thanks a million!

**Comment by Harinlen** [comment]
Well, actually, did you configure your phonon4qt5?
I'd like to know more information about your segment fault. That seems interesting.

**Comment by iyzsong** [comment]
Nevermind, I think this should be a bug of `phonon4qt5-backend-vlc`.

**Comment by Harinlen** [comment]
Thanks! I'd like to know these: 
1. Can you reappear this problem? 
2. Is this problem happened for only one file or all files? 
3. Have you install the codec of the music file?

**Comment by Harinlen** [comment]
A bug of `phonon4qt5-backend-vlc`...?
I...think...it...seems...impossible..............? (((0_0)))

**Comment by iyzsong** [comment]
Yes, I can reproduce this, with:
  remove `phonon4qt5-backend-gstreamer` and `phonon4qt5-backend-vlc`, OK.
  install `phonon4qt5-backend-vlc`, mu got segment fault without any output..
  install `phonon4qt5-backend-gstreamer` (whether `phonon4qt5-backend-vlc` installed or not), OK.

IMO, `phonon` is not well supported by Qt5, the alternatives are QtMultimedia and Gstreamer (use it directly).

**Comment by Harinlen** [comment]
Actually, did you know the 'dark side of the QtMultiMedia'?
I've already tried to use QtMultimedia module for a long time. It caused really bad effects.

**Comment by Harinlen** [comment]
Here's a part of mailing copy of from Qt mailing list.

---
Hi Massimo et alia,

I am well aware you guys do your best to provide a quality cross-platform framework and so far you did an excellent job !
Unfortunately I cannot say such thing for the Qt Multimedia module. If you stick to the provided examples (properly tailored to hide all the bugs) they all almost work. If you try to use the multimedia functionalities in a serious project and try to deploy it, then the pain comes around.
I found Qt Multimedia buggy, unsupported and moreover not cross-platform.

I am the maintainer of an open source project and so far I provided multimedia audio input/output on Qt4 using ALSA on Linux, WAVEIN/WAVEOUT on Windows and PortAudio on OSX.
In the last 9 months I tried to switch to Qt5 Multimedia and opened a number of issues on JIRA and none of them has been resolved or taken into account.

It seems the priority goes to things like Camera input, instead of fixing and consolidating the current functionalities.
As of today, on Gerrit there are only 12 open commits. 5 of them related to Camera input. 9 of them are 4 or more months old.
https://codereview.qt-project.org/#/q/status:open+project:qt/qtmultimedia,n,z
On JIRA there 178 open tickets. More than 100 are P1 or P2 but it seems nobody is actively taking care of them:
https://bugreports.qt-project.org/browse/QTBUG/component/19173#selectedTab=com.atlassian.jira.plugin.system.project%3Acomponent-issues-panel

So the question is, are you guys actually interested in improving Qt Multimedia ?
Is there any internal problem in maintaining this module that we should be aware of ?

Please let us know something about the future of this module, cause right now it is quite difficult to rely on it and include it on a project.
I would offer my contribution to fix some of the issues I found, but unfortunately my time is very limited and I'd risk to not being able to follow the activities.

My personal suggestion: to take this seriously you need 2-3 developers working 8 hours a day on this module. At least until it reaches the quality of the other Qt modules.
---
The problem you are describing here is true and is something that needs to be addressed.  I held a discussion at the 2014 Qt contributors summit and said basically the same thing.  QtMultimedia contains a rather large set of APIs but for most platforms there are huge gaps in the features available.  The problem as you stated has to do with resources and prioritisation.  The number of “active” QtMultimedia contributors can be counted on 1 hand, and almost all of the work requires detailed knowledge of the native multimedia APIs for each platform.  This leads to a situation where only the most important bugs on the most used platforms get fixed, and the other serious bugs will stay in the queue.  Qt has a huge scope yet a finite amount of development resources. QtMultimedia is a victim of the prioritisation of developer resources.

With the current state of QtMultimedia, it is not uncommon for users who have a heavy dependance of multimedia functionality to use the native API’s directly rather than using QtMultimedia.

A bit of history for those of you who don’t know.  QtMultimedia was developed and maintained in Brisbane, Australia by the Qt team in Nokia.  When Nokia divested in Qt, they closed the Brisbane office and suddenly the QtMultimedia team ceased to exist.  At this point Qt 5.0.0 had not yet been released, and many other modules that had been the responsible of the Brisbane team were dropped due to being unfinished, but still “add-ons”.  QtMultimedia being considered an “essential” module was not dropped, but was still unfinished.  3 developers then with Digia (myself included) volunteered to contribute part-time to QtMultimedia to try and get it up to a “usable” state for release, but there was a considerable amount of work left come release time.  The decision was made to keep the module in the release despite the many gaps in functional of the various backends because of it’s essential nature.  Since the release we have added at least 3 additional platform backends (iOS, Android, WinRT) each of which usually have both a high-level multimedia backend as well as a low level audio API.  This succeeded in spreading us even more thin regarding developer resources.  

It is worth mentioning that while I am no longer working with QtMultimedia, Yoann who is the current maintainer of QtMultimedia module is working full-time on it.  There have also been contributions towards GStreamer 1.x support recently that has been greatly appreciated.

Now is a great time to become a contributor to QtMultimedia as it definitely needs some love.  If anyone is interested in becoming a contributor to QtMultimedia I would be happy to answer questions to help get you up to speed.

Regards,
Andy Nichols
---
 Have you considered using Phonon? Not the ancient version bundled with Qt 4, 
 but the real thing, directly from the KDE developers? It can also be built 
 against Qt 5 now.
 
        Kevin Kofler
---
Phonon ?!?!
Please can you give us some links to this Phonon for Qt5 ?
On which platform has been ported Phonon ? I really need a good multimedia module for android and iOS.

Thanks,
Gianluca.

**Comment by iyzsong** [comment]
The problem may relate to vlc, which just build a qt4 plugins in /usr/lib/vlc/.
I don't know anything about QtMultimedia, you can safely ignore my suggestion ;-)

**Comment by iyzsong** [comment]
OK, uninstall `vlc` (which include qt4 gui), but keep `vlc-nox` does the trick.

**Comment by Harinlen** [comment]
Oh! I've know that bug you are talking about. 
On my Ubuntu 14.10 (VBox), I installed the VLC player, and Qt 4 caused several unknown issues with Qt 5. So I tried to delete the Qt 4 dll file and all the issues solved.
I'd like to write a Qt Multimedia module for optional choice. You can tried to compile with that module. Thx a lot.

**Comment by Harinlen** [comment]
You can tried to enable the VLC backend for testing this issue. If it can nicely work, then the Qt 4 plugin might be the reason.
I'm still finding the best way to solve this problem. I've already started a new project named 'Eri' for cross-platform music playing. But I find out that there's a lot of things to do. I find out that Qt Multimedia and phonon had done really good job.

**Comment by iyzsong** [comment]
IMO, `gstreamer' is the best stable and featureful multimedia framework.
It have good documents and a great community, I would choose this way :XD.
(just my thought)

**Comment by Harinlen** [comment]
I'd like to try `gstreamer`, and I've read some documentation about gstreamer. Probably I may can have a try to write a gstreamer-backend?
So, if you'd like to, I may add a gstreamer-backend for future options. Could you please help us test gstreamer when we done that? Well, it can't be done in the resent versions. I'm sorry for this :(

**Comment by iyzsong** [comment]
I'm planing to play with gstreamer too, looking forward it it!

**Pull request merged**
