### PR TITLE
Fix spelling and grammar mistakes in Readme.md

### PR DESCRIPTION
**Pull request by nick70**

### CODE REVIEW

**Comment by nick70** [comment]
Thanks

I updated the commit with those changes

**Comment by nick70** [comment]
I didn't realize I could "View changes".. oh well lol

**Comment by frantic1048** [comment]
Sorry for the unclear description. You did exactly what I mean. Thanks.

@Harinlen Captain, we have a PR.

**Comment by Harinlen** [comment]
Cool. Thanks for your help. I really appreciate it.

**Pull request merged**
